[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = 'has("nvim")'
on_i = 1
hook_add = '''
  set runtimepath+=~/.cache/dein/repos/github.com/Shougo/deoplete.nvim
  let g:deoplete#enable_at_startup = 1

  call deoplete#custom#option({
  \ 'auto_complete_delay': 0,
  \ 'max_list': 10000,
  \ 'camel_case': v:false,
  \ 'ignore_case': v:false,
  \ 'refresh_always': v:false,
  \ 'smart_case': v:true,
  \ 'buffer_path': v:true
  \ })

  call deoplete#custom#var('buffer_path', v:true)
'''

[[plugins]]
repo = 'Shougo/neomru.vim'
on_path = '.*'

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_path = '.*'
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet'
depends = ['neosnippet-snippets']
on_i = 1
on_ft = ['snippet']

[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = ['md', 'markdown']

[[plugins]]
repo = 'joker1007/vim-markdown-quote-syntax'
on_ft = ['md', 'markdown']

# [[plugins]]
# repo = 'kannokanno/previm'
# on_ft = ['md', 'markdown']

[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
on_ft = ['md', 'markdown', 'pandoc.markdown', 'rmd']
build = 'cd app & yarn install'

[[plugins]]
repo = 'iamcco/mathjax-support-for-mkdp'
on_ft = ['md', 'markdown', 'pandoc.markdown', 'rmd']

[[plugins]]
repo = 'psf/black'
on_ft = ['python']

[[plugins]]
repo = 'nvie/vim-flake8'
on_ft = ['python']

[[plugins]]
repo = 'fisadev/vim-isort'
on_ft = ['python']

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = ['python']

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'
